libs =
import libs += libensketch-xstd%lib{ensketch-xstd}

import libs += fmt%lib{fmt}
import libs += libreplxx%lib{replxx}
import libs += libchaiscript%lib{chaiscript}
import libs += libgeometrycentral%lib{geometrycentral}
import libs += libigl-core%liba{igl-core}

import libs += sol2%lib{sol2}

import libs += glbinding%lib{glbinding}
import libs += glm%lib{glm}
import libs += libsfml-graphics%lib{sfml-graphics}

import libs += assimp%lib{assimp}

import libs += libcino%lib{cino}

import libs += stb_image_write%lib{stb_image_write}

exe{ensketch-sandbox}: {hxx ixx txx cxx}{**} $libs
{
  test = true
#   test.arguments = $src_base/config.chai
}

out_pfx = [dir_path] $out_root/sources/
src_pfx = [dir_path] $src_root/sources/

cxx.poptions =+ "-I$out_pfx" "-I$src_pfx"
