libs =
import libs += libreplxx%lib{replxx}
import libs += libchaiscript%lib{chaiscript}

exe{ensketch-sandbox}: {hxx ixx txx cxx}{**} $libs
{
  test = true
}

out_pfx = [dir_path] $out_root/sources/
src_pfx = [dir_path] $src_root/sources/

cxx.poptions =+ "-I$out_pfx" "-I$src_pfx"
